version: '3.8'

services:
  google-analytics-mcp:
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/application_default_credentials.json
    restart: unless-stopped
    networks:
      - mcp-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - google-analytics-mcp
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
